import { Company, decimal, itemTotals, money, Order, totals, windowTotal } from './model';
export const escape = (s: string) => s.replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]!));
export function orderHtml(order: Order, company: Company) {
  const c = order.company ?? company;
  const t = totals(order);
  const logo = c.logo && /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(c.logo) ? `<img class="logo" src="${c.logo}" alt="Sigla magazinului">` : '';
  const windows = order.windows.map((w, n) => {
    const sewingGroups = new Map<string, {style: string; rate: number; quantity: number; amount: number}>();
    const items = w.items.map(i => {
      const v = itemTotals(i, w);
      const details = [i.code, i.style, i.kind === 'area' ? `${decimal(i.width)} × ${decimal(i.height)} cm · ${i.quantity} buc.` : ''].filter(Boolean).map(escape).join(' · ');
      const row = `<tr><td>${escape(i.name)}${details ? `<small>${details}</small>` : ''}</td><td>${decimal(v.quantity)} ${v.unit}</td><td>${money(i.price)}</td><td>${money(v.material)}</td></tr>`;
      if (i.kind === 'curtain' && i.sewing > 0) {
        const key = JSON.stringify([i.style, i.sewing]);
        const group = sewingGroups.get(key) ?? {style: i.style, rate: i.sewing, quantity: 0, amount: 0};
        group.quantity += v.quantity; group.amount += v.sewing;
        sewingGroups.set(key, group);
      }
      return row;
    }).join('');
    const sewingRows = [...sewingGroups.values()].map(g => `<tr><td>Manoperă croitorie${g.style ? `<small>${escape(g.style)}</small>` : ''}</td><td>${decimal(g.quantity)} m</td><td>${money(g.rate)}</td><td>${money(g.amount)}</td></tr>`).join('');
    return `<tbody class="window"><tr class="window-title"><td colspan="4">FEREASTRA ${n+1}${w.name ? ' — '+escape(w.name) : ''} · Lățime: ${decimal(w.width/100)} m · Înălțime: ${w.height ? decimal(w.height/100)+' m' : '—'}</td></tr>${items}${sewingRows}<tr class="subtotal"><td colspan="3">Total fereastra ${n+1}</td><td>${money(windowTotal(w))}</td></tr></tbody>`;
  }).join('');
  return `<!doctype html><html lang="ro"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(order.number || 'Ciornă')}</title><style>
  @page{size:A4;margin:0}*{box-sizing:border-box}body{font-family:Arial,sans-serif;font-size:11px;color:#243544;margin:0;padding:12mm;background:#fff}header{display:grid;grid-template-columns:1fr 1fr 1fr;gap:22px;margin-bottom:22px}header h2{font-size:16px;margin:0 0 10px}header p{margin:5px 0;white-space:pre-wrap;overflow-wrap:anywhere}header .command{font-size:10px;text-align:center}header .command h2{font-size:12px}header .client{padding-left:30px}.logo{max-width:110px;max-height:45px;object-fit:contain;margin-bottom:7px}table{width:100%;border-collapse:collapse;table-layout:fixed}th{font-size:10px;padding:9px 6px;border-top:1px solid #d5dfe5}th:first-child{text-align:left;width:48%}th:nth-child(2){width:16%}th:nth-child(3){width:18%}th:nth-child(4){width:18%}th:not(:first-child),td:not(:first-child){text-align:right}td{padding:4px 6px;vertical-align:top;overflow-wrap:anywhere}small{display:block;font-size:9px;color:#61727f;margin-top:2px}.window{break-inside:avoid;page-break-inside:avoid}.window-title td{text-align:left;background:#edf2f6;font-size:12px;padding:8px 6px}.subtotal td{padding:8px 6px 10px;border-bottom:1px solid #d5dfe5}.subtotal td:first-child{text-align:right}.subtotal td:last-child{font-weight:bold}.bottom{display:grid;grid-template-columns:1fr 1fr;gap:25px;margin-top:18px;padding-top:12px;border-top:1px solid #d5dfe5;break-inside:avoid}.bottom h3{font-size:12px;margin:0 0 12px}.bottom p{margin:7px 0}.account p{display:flex;justify-content:space-between;gap:12px}.account .strong{font-weight:bold;font-size:13px}.conditions{margin-top:18px;border-top:1px solid #d5dfe5;padding-top:10px;font-size:9px;line-height:1.45;break-inside:avoid}.conditions h3{font-size:10px;margin:0 0 6px}.conditions p{margin:3px 0}.signatures{display:flex;justify-content:space-between;gap:25px;margin-top:30px;padding-bottom:15px;font-size:11px;break-inside:avoid}.draft{text-align:center;color:#8a5c19;margin-bottom:12px}thead{display:table-header-group}@media screen{body{max-width:794px;margin:auto;padding:24px}}
  </style></head><body>${order.status === 'draft' ? '<div class="draft">CIORNĂ — COMANDĂ NECONFIRMATĂ</div>' : ''}<header><section>${logo}<h2>${escape(c.name)}</h2><p>${escape(c.address)}</p><p>${escape(c.phone)}</p></section><section class="command"><h2>FIȘĂ DE COMANDĂ</h2><p>Nr. comandă: ${escape(order.number || 'Ciornă')}</p><p>Data: ${escape(order.date)}</p>${order.revision > 1 ? `<p>Revizia: ${order.revision}</p>` : ''}</section><section class="client"><h2>DATE CLIENT</h2><p>${escape(order.customer)}</p><p>Tel.: ${escape(order.phone)}</p><p>${escape(order.address)}</p></section></header><table><thead><tr><th>PRODUS</th><th>CANTITATE</th><th>PREȚ UNITAR</th><th>VALOARE</th></tr></thead>${windows}</table><section class="bottom"><div><h3>LIVRARE ȘI MONTAJ</h3><p>Data livrării: ${escape(order.delivery || '—')}</p><p>Montaj solicitat: ${order.installation ? 'Da' : 'Nu'}</p><p>Cost montaj: ${money(t.installation)}</p></div><div class="account"><p><span>Subtotal</span><span>${money(t.subtotal)}</span></p>${order.discount ? `<p><span>Reducere</span><span>${money(order.discount)}</span></p>` : ''}<p class="strong"><span>TOTAL</span><span>${money(t.total)}</span></p><p><span>Avans / plăți achitate</span><span>${money(t.paid)}</span></p><p class="strong"><span>REST DE PLATĂ</span><span>${money(t.remaining)}</span></p></div></section><section class="conditions"><h3>CONDIȚII DE COMANDĂ</h3>${c.conditions.split('\n').filter(Boolean).map(line => `<p>${escape(line)}</p>`).join('')}</section><section class="signatures"><span>Semnătura clientului: ____________________</span><span>Data semnării: ______________</span></section></body></html>`;
}
