import { chromium, webkit } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

await mkdir('artifacts', {recursive: true});
const browser = process.env.ATELIER_WEBKIT ? await webkit.launch({headless:true}) : await chromium.launch({executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true});
const page = await browser.newPage({viewport: {width: 390, height: 844}, deviceScaleFactor: 1});
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('dialog', dialog => dialog.accept());
try {
  if (process.env.ATELIER_BROWSER_URL?.startsWith('file:')) await page.context().setOffline(true);
  await page.goto(process.env.ATELIER_BROWSER_URL || 'http://localhost:8081', {waitUntil: 'networkidle'});
  await page.getByLabel('Denumire magazin', {exact: true}).fill('MAGAZIN TEST');
  await page.getByLabel('Adresă magazin', {exact: true}).fill('Str. Exemplu nr. 10');
  await page.getByLabel('Telefon magazin', {exact: true}).fill('0712345678');
  await page.getByRole('button', {name: 'Salvează setările', exact: true}).click();
  await page.getByText('Comenzi', {exact: true}).click();
  await page.getByRole('button', {name: 'Deschide exemplul cu 5 ferestre', exact: true}).click();
  await page.getByText('2. Ferestre', {exact: true}).click();
  await page.getByRole('button', {name: '+ Adaugă produs', exact: true}).first().click();
  await page.getByText('Plisse / jaluzea · m²', {exact: true}).click();
  await page.getByLabel('Denumire produs', {exact: true}).fill('Plisse test');
  await page.getByLabel('Preț / m² (lei)', {exact: true}).fill('200');
  await page.getByLabel('Lățime produs (cm)', {exact: true}).fill('60');
  await page.getByLabel('Înălțime produs (cm)', {exact: true}).fill('100');
  await page.getByLabel('Număr de bucăți', {exact: true}).fill('2');
  await page.getByLabel('Suprafață facturată / bucată (m², opțional)', {exact: true}).fill('1');
  await page.getByRole('button', {name: 'Salvează produsul', exact: true}).click();
  await page.getByRole('button', {name: '+ Adaugă produs', exact: true}).first().click();
  await page.getByText('Accesorii / galerie · buc.', {exact: true}).click();
  await page.getByLabel('Denumire produs', {exact: true}).fill('Accesoriu test');
  await page.getByLabel('Preț / bucată (lei)', {exact: true}).fill('150');
  await page.getByLabel('Număr de bucăți', {exact: true}).fill('4');
  await page.getByRole('button', {name: 'Salvează produsul', exact: true}).click();
  await page.screenshot({path: 'artifacts/ferestre.png', fullPage: true});
  await page.getByText('4. Rezumat', {exact: true}).click();
  await page.getByRole('button', {name: 'Confirmă și salvează comanda', exact: true}).click();
  await page.getByText('CMD-00001', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Previzualizează formularul', exact: true}).click();
  const frame = page.frameLocator('iframe[title="Fișa de comandă"]');
  await frame.locator('td').filter({hasText: 'Plisse test'}).first().waitFor();
  await frame.locator('td').filter({hasText: 'Accesoriu test'}).first().waitFor();
  await frame.getByText('Semnătura clientului:', {exact: false}).waitFor();
  await page.screenshot({path: 'artifacts/formular.png', fullPage: true});
  const pdfPage = await browser.newPage();
  const html = await frame.locator('html').evaluate(node => node.outerHTML);
  await pdfPage.setContent(html);
  if (!process.env.ATELIER_WEBKIT) await pdfPage.pdf({path: 'artifacts/formular-din-aplicatie.pdf', format: 'A4', printBackground: true});
  await page.getByRole('button', {name: 'Închide', exact: true}).click();
  const printPopupPromise = page.waitForEvent('popup');
  await page.getByRole('button', {name: 'PDF · Salvează / distribuie', exact: true}).click();
  const printPopup = await printPopupPromise;
  await printPopup.getByText('FIȘĂ DE COMANDĂ', {exact: true}).waitFor();
  await printPopup.locator('td').filter({hasText: 'Plisse test'}).first().waitFor();
  await printPopup.close();
  await page.getByText('‹ Comenzi', {exact: true}).click();
  await page.reload({waitUntil: 'networkidle'});
  await page.getByText('Client Exemplu', {exact: true}).waitFor();
  const text = await page.locator('body').innerText();
  if (!text.includes('25.475,00')) throw new Error('Incorrect stored balance');
  await page.screenshot({path: 'artifacts/comenzi.png', fullPage: true});
  await page.getByText('Client Exemplu', {exact: true}).click();
  await page.getByLabel('Nume client', {exact: true}).fill('Client Actualizat');
  await page.getByText('4. Rezumat', {exact: true}).click();
  await page.getByRole('button', {name: 'Salvează comanda', exact: true}).click();
  await page.waitForTimeout(500);
  await page.getByText('‹ Comenzi', {exact: true}).click();
  await page.getByText('Vezi reviziile anterioare', {exact: true}).click();
  await page.getByText('Revizia 1', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Închide', exact: true}).click();
  await page.getByText('Magazin și backup', {exact: true}).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', {name: 'Exportă backup', exact: true}).click();
  const download = await downloadPromise;
  await download.saveAs('artifacts/backup.json');
  const chooserPromise = page.waitForEvent('filechooser');
  await page.getByRole('button', {name: 'Restaurează din backup', exact: true}).click();
  const chooser = await chooserPromise;
  await chooser.setFiles('artifacts/backup.json');
  await page.waitForTimeout(1000);
  await page.getByText('Comenzi', {exact: true}).click();
  await page.getByText('Client Actualizat', {exact: true}).waitFor();
  page.removeAllListeners('dialog');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', {name: 'Șterge comanda CMD-00001', exact: true}).click();
  await page.getByText('Client Actualizat', {exact: true}).waitFor();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', {name: 'Șterge comanda CMD-00001', exact: true}).click();
  await page.getByText('Prima comandă începe aici', {exact: true}).waitFor();
  await page.reload({waitUntil: 'networkidle'});
  await page.getByText('Prima comandă începe aici', {exact: true}).waitFor();
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('PASS: company setup, m² products, accessories, PDF/print, persistence, revisions, backup, delete cancellation/confirmation and persistent deletion.');
} catch(e) {
  await page.screenshot({path: 'artifacts/failure.png', fullPage: true});
  console.log(await page.locator('body').innerText());
  throw e;
} finally {await browser.close();}
